# Generated by Django 2.2.10 on 2020-04-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplatters',
            old_name='price',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='regularpizza',
            old_name='price',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='sicilianpizza',
            old_name='price',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='subs',
            old_name='price',
            new_name='large',
        ),
        migrations.RemoveField(
            model_name='dinnerplatters',
            name='size',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='subs',
            name='size',
        ),
        migrations.AddField(
            model_name='dinnerplatters',
            name='small',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regularpizza',
            name='small',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='small',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subs',
            name='small',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
