# Generated by Django 2.2.10 on 2020-05-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_regularpizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sicilianpizza',
            name='image',
            field=models.ImageField(blank=True, upload_to='sicilianpizza_img'),
        ),
    ]
