# Generated by Django 2.2.10 on 2020-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_sicilianpizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplatters',
            name='image',
            field=models.ImageField(blank=True, upload_to='dinnerplatters_img'),
        ),
        migrations.AddField(
            model_name='pasta',
            name='image',
            field=models.ImageField(blank=True, upload_to='pasta_img'),
        ),
        migrations.AddField(
            model_name='salads',
            name='image',
            field=models.ImageField(blank=True, upload_to='salads_img'),
        ),
        migrations.AddField(
            model_name='subs',
            name='image',
            field=models.ImageField(blank=True, upload_to='subs_img'),
        ),
    ]
