# Generated by Django 2.2.10 on 2020-06-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200530_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='image',
            field=models.ImageField(blank=True, upload_to='regularpizza_img'),
        ),
    ]
